### PR TITLE
Version upgrade

### PR DESCRIPTION
**Pull request by michaelmior**
This is a fairly sizeable collection of version upgrades to various services in the VM. I would normally prefer to try to break this down into smaller changes, but given the scope it seemed easier to do things wholesale. The biggest change is moving to Ubuntu 16.04 from 14.04. I also upgrade all of the Puppet modules which means some version upgrades for some of the services. I ran integration tests for Cassandra, MongoDB, and Elasticesearch which all pass. Tests for Druid still pending.

### CODE REVIEW

**Comment by julianhyde** [comment]
This is very welcome, but let's get the Druid tests to pass before we commit. Previous attempts to upgrade Druid have caused problems with Druid failing to initialize its data (perhaps due to lack of memory) and therefore the VM just isn't useful for Calcite development.

**Comment by michaelmior** [comment]
Agreed. I have no problem loading the data in Druid (although it is a little slow). However, the integration tests seem to just hang and nothing happens.

**Comment by julianhyde** [comment]
@michaelmior, Now that the Druid upgrade has gone in (see f5de94f42c062140bccbd9152607000e375b911b) I've rebased your PR as https://github.com/julianhyde/calcite-test-dataset/tree/version-upgrade. I am running Calcite tests now.

**Comment by michaelmior** [comment]
@julianhyde Thanks! Updated the PR to match your branch.

**Comment by julianhyde** [comment]
I get some errors:

```
==> ubuntucalcite: Notice: /Stage[main]/Main/Node[ubuntucalcite]/Elasticsearch::Instance[calcite]/Elasticsearch::Service[calcite]/Elasticsearch::Service::Systemd[calcite]/Service[elasticsearch-instance-calcite]: Dependency Archive[/usr/java/jre-8u121-linux-x64.tar.gz] has failures: true
==> ubuntucalcite: Warning: /Stage[main]/Main/Node[ubuntucalcite]/Elasticsearch::Instance[calcite]/Elasticsearch::Service[calcite]/Elasticsearch::Service::Systemd[calcite]/Service[elasticsearch-instance-calcite]: Skipping because of failed dependencies
```

and

```
==> ubuntucalcite: Inappropriate ioctl for device
==> ubuntucalcite: Importing zips dataset
==> ubuntucalcite: /tmp/vagrant-shell: line 19: mongoimport: command not found
```

**Comment by michaelmior** [comment]
Thanks for trying this out. I'll try to give those a closer look later this week.

**Comment by michaelmior** [comment]
Update: MongoDB loads everything fine for me in the VM. Note that for the integration tests to pass, you need to apply the patch from [CALCITE-1697](https://issues.apache.org/jira/browse/CALCITE-1697). Still checking Elasticsearch in more detail, but the integration tests also pass there.

**Comment by julianhyde** [comment]
What's the patch for CALCITE-1697?

**Comment by michaelmior** [comment]
Whoops, sorry. Forgot that I hadn't posted anything on the JIRA. It's just [this commit](https://github.com/michaelmior/calcite/commit/d3042692e996f58d29e4cf4d2f85f28d035077d3) which updates the MongoDB driver version.

**Comment by vvysotskyi** [comment]
I also observed the same error:
```
Dependency Archive[/usr/java/jre-8u121-linux-x64.tar.gz] has failures
```
To avoid it helped changing `aco-oracle_java` version to 2.8.1 (the same version is on current master). Also, should be used ruby2.3 and gem2.3 instead of 2.0, since they are absent in the repository for 16.04. Another failure I had connected with postgres version, so I reverted it back to 4.7.0.

I rebased this PR and made changes specified above and VM started. But for some reason, Druid tables weren't populated and queries for this module failed.

Can we continue work on this PR, since updating mongodb version for calcite-test-dataset should be done before merging https://github.com/apache/calcite/pull/720?

**Comment by vvysotskyi** [comment]
Tried just to update Mongo, but hit the same problem with Druid tables. It happens due to the RAM lack.

**Pull request closed without merging**
