### PR TITLE
Cassandra integration

### PR DESCRIPTION
**Pull request by michaelmior**
There is an open pull request (apache/calcite#195) to add a Cassandra adapter to Calcite. Before this can land, there would need to be Cassandra support here. This just adds a Cassandra module and sample data.

One oddity is that for some reason the new version of the mongodb module (which I had to upgrade) does not create the directory for the pid file. The current setup explicitly creates this with global read/write permissions. This is definitely a hack but given that this VM is only used for testing, I don't think this is a big concern.

### CODE REVIEW

**Comment by julianhyde** [comment]
Can you add a Cassandra entry in https://github.com/michaelmior/calcite-test-dataset/tree/cassandra#list-of-created-databases

And as I noted in https://issues.apache.org/jira/browse/CALCITE-1080 there may be a problem with the postgres instance.

**Comment by vlsi** [comment]
@michaelmior, it looks odd that some of the files (e.g. timeline.csv) in crlf, while others are in lf format.

I think `.gitattributes` should be added to make that consistent.
Can you please add it with the following contents?

```
* text=auto
*.sh text eol=lf
*.java text
*.sql text
*.csv text
*.yaml text
*.yml text
```

**Comment by michaelmior** [comment]
@julianhyde Added the note in the README. Looking into the test failures. The postgres database appears to work for me, but I can't get the tests to successfully execute even without my changes here. With a fresh checkout of both repositories, I did the following

```
cd calcite-test-dataset
mvn install
cd ../calcite
mvn verify -Pit -Dcalcite.test.db=postgresql -pl core
```

I still get several test failures.

@vlsi That is odd about the line endings. They were all generating using the same command to dump data from Cassandra. Regardless, I added the `.gitattributes` file.

**Comment by julianhyde** [comment]
I think it's unlikely that the postgres failures are due to your changes to calcite, but likely that they are due to your changes to calcite-test-dataset and therefore to the VM. (I believe that if I run your calcite branch against the master calcite-test-dataset, the postgres test succeeds. I'll check.)

You say you get errors when you run the postgres test against the master calcite-test-dataset. If so can you post them?

**Comment by michaelmior** [comment]
@julianhyde I agree with your assessment. That's why I was surprised to see the tests fail. I'll run again and send the failed output.

**Comment by julianhyde** [comment]
OK, I checked. `mvn verify -Pit -Dcalcite.test.db=postgresql -pl core` succeeds on https://github.com/julianhyde/calcite/tree/1080-cassandra and https://github.com/vlsi/calcite-test-dataset/tree/master.

**Comment by michaelmior** [comment]
Odd. That failed for me. Good to know it's not broken on master anyway. I'll dig into this and post more when I have an update.

**Comment by michaelmior** [comment]
It looks like this was caused by my previous work in #3. I inadvertently removed the creation of the schema and I must have failed to properly test. I added that back here. It might be good to cherry pick that last commit into master (or I can open up a separate PR). My apologies for the slip up there.

Anyway, all the tests now pass for me. Actually, I'm a little stumped as to why they passed for @julianhyde since I would expect master to be broken.

**Comment by vlsi** [comment]
@michaelmior , followers.csv and friends.csv files are empty. Is that intended?

**Comment by michaelmior** [comment]
@vlsi Yes. There is currently no data populated in those tables.

**Comment by julianhyde** [comment]
The full Calcite test suite now passes for me on @michaelmior's VM, on both Calcite main and on the cassandra branch. So, +1 after you've squashed commits.

**Comment by michaelmior** [comment]
Squashed. Thanks for the help reviewing!

**Comment by vlsi** [comment]
Thanks for the contribution.

Here's what I get for https://github.com/apache/calcite/pull/195:

```
[INFO] Reactor Summary:
[INFO]
[INFO] Calcite Core ....................................... SUCCESS [06:13 min]
[INFO] Calcite Cassandra .................................. SUCCESS [  8.442 s]
[INFO] Calcite Dropwizard Reporter for Hadoop Metrics2 .... SUCCESS [  4.026 s]
[INFO] Calcite Examples ................................... SUCCESS [  0.233 s]
[INFO] Calcite Example CSV ................................ SUCCESS [  3.822 s]
[INFO] Calcite Example Function ........................... SUCCESS [  2.836 s]
[INFO] Calcite MongoDB .................................... SUCCESS [ 30.116 s]
[INFO] Calcite Piglet ..................................... SUCCESS [  3.527 s]
[INFO] Calcite Plus ....................................... SUCCESS [  2.802 s]
[INFO] Calcite Spark ...................................... SUCCESS [  2.567 s]
[INFO] Calcite Splunk ..................................... SUCCESS [  2.208 s]
[INFO] Calcite Ubenchmark ................................. SUCCESS [  3.794 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
```

**Comment by michaelmior** [comment]
@vlsi Thanks for the merge!

**Pull request closed without merging**
