### PR TITLE
update druid to 0.9.2.

### PR DESCRIPTION
**Pull request by b-slim**
This change is [Reviewable](https://reviewable.io/reviews/vlsi/calcite-test-dataset/17)

### CODE REVIEW

**Comment by b-slim** [comment]
@julianhyde checkout this please.

**Comment by julianhyde** [comment]
Your script does pretty much the same as mine in https://github.com/julianhyde/calcite-test-dataset/tree/druid-0.9.2, and it has the same problem.

Did you try the two sanity checks in https://github.com/vlsi/calcite-test-dataset#accessing-druid-in-the-vm ? For me the curl command just hangs.

**Comment by b-slim** [comment]
@julianhyde i had to increase the ram, i am thinking about changing the start script to use custom made jvm conf.

**Comment by jcamachor** [comment]
@b-slim , @julianhyde , what is the status? I think it would be good to move to 0.9.2. Could we increase the ram in the VM config and merge it?

**Comment by julianhyde** [comment]
We can't push up the memory too high. We want this VM to be usable by people doing development on laptops.

I would appreciate if @b-slim took a look at the Druid logs and figure out what's going wrong with Druid. It might not be just memory.

#18 is another initiative to upgrade Druid, but goes further, upgrading Linux and Cassandra also. Let's combine forces with that.

**Comment by vlsi** [comment]
Alternative option is to split the VM into several ones (and start only a fraction of them). At the end of the day, we might have troubles fitting all the DBs into a single VM.

**Comment by julianhyde** [comment]
Or, have a Docker image for each test DB, so that people can start just the ones they need, with lower overhead than a full VM for each DB.

Regardless, we need to figure out why Druid is using so much memory.

**Comment by b-slim** [comment]
currently the scripts try to [start the druid nodes](https://github.com/b-slim/calcite-test-dataset/blob/9700bf9b9793a45e40872a9d46dbc868527f6d5d/foodmart-dataset/src/main/resources/druid/run.sh#L22-L22) with an `Xms` of 1G hence the high usage of memory.

**Comment by b-slim** [comment]
i think Docker image is a good idea.

**Comment by b-slim** [comment]
@julianhyde will be looking at changing the amount of memory used by druid. Other than that i think some changes might need to be done on the parser side from calcite looking into that as well.

**Pull request closed without merging**
